### ISSUE TITLE
Handle Pandanet IGS SGF files with "Copyright" info

### ISSUE THREAD

**Issue by varenius** [Kashomon/glift#101]
Recent files from the Pandanet IGS website from the European Team Championships (http://pandanet-igs.com/communities/euroteamchamps/rounds/226) contain the following info in the SGF:
CoPyright[
  Copyright (c) PANDANET Inc. 2014
  Permission to reproduce this game is given, provided proper credit is given.
  No warrantee, implied or explicit, is understood.
  Use of this game is an understanding and agreement of this notice.
]
This makes Glift fail with this console error:
"Error: SGF Parsing Error: At line [3], column [2], char [o], Unexpected character in property name"

I guess this could be handled in a nice way by glift (note the capital P in the pandanet file, which is probably also a mistake, so that any "copyright"-key should be compared by lowercase or so when reading this in glift.

**Comment by yewang** [comment]
I know this already a closed issue, but I thought I should point out that lowercase letters were allowed in property identifiers for FF[1]-FF[3], and only FF[4] forbids lowercase letters. Since Pandanet's SGF files omit the FF property, I suppose the FF[1] default applies, which technically seems to mean that their files are valid and just following an older standard.

For these older file formats, lowercase letters in property identifiers were simply ignored, and only the remaining uppercase letters would be interpreted. Hence,
CoPyright => CP
White => W
thisaBlackmove => B

The guide for converting older file formats discusses this issue:
http://www.red-bean.com/sgf/converting.html

Accounting for this would be necessary for dealing with older, but valid, file formats.
